version: '3'
services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nest-bank-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    env_file:
      - ./env/app/.news.env
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: nest-bank-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    env_file:
      - ./env/postgres/.porstgres.env
